### ISSUE TITLE
Add #connectIfNotAlreadyFollowingProperty:context:

### ISSUE THREAD

**Issue by jecisc** [TelescopeSt/Telescope#74]
I did some visualizations this week and in some case, I had multiple links between entities.

To avoid that I complexified the code to get the behavior I wanted. It is bad. I see two solutions:
- We change the method to use #connectIfNotTo: instead of #connectTo: 
- We add a #connectIfNotFollowingProperty:context:

The choice will be done depending on if we accept or not that #connectFollowingProperty: creates duplicated links? @Larcheveque ?

**Comment by Larcheveque** [comment]
I prefer the second solution (#connectIfNotFollowingProperty:context:)  because in my opinion the link must be always created in #connectFollowingProperty:context: , especially if i apply a style on the created connection to differentiate two different kinds of connections.

**Comment by jecisc** [comment]
Selled!

**Comment by Larcheveque** [comment]
Must find another name because #connectIfNotFollowingProperty:context: means that we will connect everything that is not following the property

**Comment by jecisc** [comment]
#connectIfNotAlreadyFollowingProperty:context:?
