### ISSUE TITLE
Entities should be hideable/removable from visualizations

### ISSUE THREAD

**Issue by NicolasAnquetil** [TelescopeSt/Telescope#78]
In visualizations, it would be helpful to be able to "hide" or remove entities from them so as to concentrate on the important stuff of the visualization.

For example, on the TLCycleDependencies, one could hide the entities not in cycles to have a cleaner visualization.

As this is general to all visualization, it seems best to allow this on a per-entity basis, for example, have a "hide entities" button and selected, all entities clicked would be hidden from the visualization as well as their links.

**Comment by jecisc** [comment]
You can use #hide to do that. 

If it’s on an interaction there is a Show or Hide interaction with a demo.
